config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :slides
  end
  resources :slides
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base

  validates :name, presence: true

  has_attached_file :picture, styles: { medium: "350x350>", thumb: "100x100>", small: "35x35>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/

  self.abstract_class = true
end

app/models/slide.rb
class Slide < ApplicationRecord
end

app/controllers/admin/slides_controller.rb
class Admin::SlidesController < ApplicationController
  before_action :set_slide, only: [:show, :edit, :update, :destroy]

  # GET /admin/slides
  # GET /admin/slides.json
  def index
    @slides = Slide.all
  end

  # GET /admin/slides/1
  # GET /admin/slides/1.json
  def show
  end

  # GET /admin/slides/new
  def new
    @slide = Slide.new
  end

  # GET /admin/slides/1/edit
  def edit
  end

  # POST /admin/slides
  # POST /admin/slides.json
  def create
    @slide = Slide.new(slide_params)

    respond_to do |format|
      if @slide.save
        format.html { redirect_to [:admin, @slide], notice: 'Slide was successfully created.' }
        format.json { render action: 'show', status: :created, location: @slide }
      else
        format.html { render action: 'new' }
        format.json { render json: @slide.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/slides/1
  # PATCH/PUT /admin/slides/1.json
  def update
    respond_to do |format|
      if @slide.update(slide_params)
        format.html { redirect_to [:admin, @slide], notice: 'Slide was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @slide.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/slides/1
  # DELETE /admin/slides/1.json
  def destroy
    @slide.destroy
    respond_to do |format|
      format.html { redirect_to admin_slides_url, notice: 'Slide was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_slide
      @slide = Slide.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def slide_params
      params.require(:slide).permit(:name, :desc_left, :desc_right, :picture)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/slides_controller.rb
class SlidesController < ApplicationController
  before_action :set_slide, only: [:show, :edit, :update, :destroy]

  # GET /slides
  # GET /slides.json
  def index
    @slides = Slide.all
  end

  # GET /slides/1
  # GET /slides/1.json
  def show
  end

  # GET /slides/new
  def new
    @slide = Slide.new
  end

  # GET /slides/1/edit
  def edit
  end

  # POST /slides
  # POST /slides.json
  def create
    @slide = Slide.new(slide_params)

    respond_to do |format|
      if @slide.save
        format.html { redirect_to @slide, notice: 'Slide was successfully created.' }
        format.json { render :show, status: :created, location: @slide }
      else
        format.html { render :new }
        format.json { render json: @slide.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /slides/1
  # PATCH/PUT /slides/1.json
  def update
    respond_to do |format|
      if @slide.update(slide_params)
        format.html { redirect_to @slide, notice: 'Slide was successfully updated.' }
        format.json { render :show, status: :ok, location: @slide }
      else
        format.html { render :edit }
        format.json { render json: @slide.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /slides/1
  # DELETE /slides/1.json
  def destroy
    @slide.destroy
    respond_to do |format|
      format.html { redirect_to slides_url, notice: 'Slide was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_slide
      @slide = Slide.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def slide_params
      params.require(:slide).permit(:name, :picture, :desc_right, :desc_left)
    end
end

app/helpers/admin/slides_helper.rb
module Admin::SlidesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/slides_helper.rb
module SlidesHelper
end

app/views/admin/slides/_form.html.erb
<%= form_for ([:admin, @slide]), html: { multipart: true } do |f| %>
  <% if @slide.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(slide.errors.count, "error") %> prohibited this slide from being saved:</h2>

      <ul>
      <% @slide.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, :class=>'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :desc_left %>
    <%= f.text_area :desc_left, :class=>'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :desc_right %>
    <%= f.text_area :desc_right, :class=>'form-control' %>
  </div>

  <div class="form-group">
    <%= f.file_field :picture %>
  </div>

  <div class="actions">
    <%= f.submit :class=>'btn btn-info' %>
  </div>
<% end %>

app/views/admin/slides/_menu_content.html.erb
<%= content_for :menu_content do %>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Action <span class="caret"></span></a>
  <ul class="dropdown-menu">
    <li><a href="<%= edit_admin_slide_path %>">Edit</a></li>
    <li><%= link_to t('.destroy', :default => t("helpers.links.destroy")), admin_slide_path(s), method: :delete, data: { confirm: t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) } %></li>
    <li role="separator" class="divider"></li>
    <li><a href="#">Something else</a></li>
  </ul>
</li>
<% end %>

app/views/admin/slides/edit.html.erb
<%= render :partial => 'menu_content', :locals => { :s => @slide } %>
<div class="container">
  <div class="row">
    <div class="col-xs-1">
      <%= link_to (admin_slide_path) do %>
      <span class="glyphicon glyphicon-arrow-left"></span>
      <% end %>
    </div>
    <div class="col-xs-11">
      <h1>Editing Slide</h1>
    </div>
  </div>

  <%= render 'form', slide: @slide %>

</div>

app/views/admin/slides/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <% @slides.each do |slide| %>
    <%= link_to admin_slide_path(slide) do %>
      <div class="row border text-center">
        <div class="row">
          <h3><%= slide.name %></h3>
        </div>
        <div class="row">
          <div class="col-md-2 col-md-offset-1">
            <%= slide.desc_left %>
          </div>
          <div class="col-md-6">
            <%= image_tag slide.picture.url(:medium) %>
          </div>
          <div class="col-md-2">
            <%= slide.desc_right %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/admin/slides/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-1">
      <%= link_to (admin_slides_path) do %>
      <span class="glyphicon glyphicon-arrow-left"></span>
      <% end %>
    </div>
    <div class="col-xs-11">
      <h1>New Slide</h1>
    </div>
  </div>
  <%= render 'form', slide: @slide %>
</div>

app/views/admin/slides/show.html.erb
<%= render :partial => 'menu_content', :locals => { :s => @slide } %>
<p id="notice"><%= notice %></p>
<div class="container">
  <div class="row">
    <div class="col-xs-1">
      <%= link_to (admin_slides_path) do %>
      <span class="glyphicon glyphicon-arrow-left"></span>
      <% end %>
    </div>
    <div class="col-xs-11">
      <h1>
        <strong>Titre:</strong>
        <%= @slide.name %>
      </h1>
    </div>
  </div>
  <div class="row text-center">
    <div class="col-md-3">
      <p><strong>Description gauche :</strong></p>
      <p><%= @slide.desc_left %></p>
    </div>

    <div class="col-md-6">
      <%= image_tag @slide.picture.url(:medium) %>
    </div>

    <div class="col-md-3">
        <p><strong>Description droite :</strong></p>
        <p><%= @slide.desc_right %></p>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sliders</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="<%= slides_path %>">Brand</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><a href="<%= new_slide_path %>">New slide <span class="sr-only">(current)</span></a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">

            <%= yield :menu_content %>

            <form class="navbar-form navbar-left">
              <div class="form-group">
                <input type="text" class="form-control" placeholder="Search">
              </div>
              <button type="submit" class="btn btn-default">Submit</button>
            </form>
            <li><a href="<%= admin_slides_path %>">Interface admin</a></li>
          </ul>
        </div>
      </div>
    </nav>
    <%= yield %>
    <!-- <footer>
      <div class="container">
        <div class="row">
          <div class="col-xs-8 col-xs-offset-2 text-center">
            <p>
              OKLM
            </p>
          </div>
        </div>
      </div>
    </footer> -->
  </body>
</html>

app/views/slides/_form.html.erb
<%= form_for @slide, html: { multipart: true } do |f| %>
  <% if slide.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(slide.errors.count, "error") %> prohibited this slide from being saved:</h2>

      <ul>
      <% slide.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, :class=>'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :desc_left %>
    <%= f.text_area :desc_left, :class=>'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :desc_right %>
    <%= f.text_area :desc_right, :class=>'form-control' %>
  </div>

  <div class="form-group">
    <%= f.file_field :picture %>
  </div>

  <div class="actions">
    <%= f.submit :class=>'btn btn-info' %>
  </div>
<% end %>

app/views/slides/_menu_content.html.erb
<%= content_for :menu_content do %>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Action <span class="caret"></span></a>
  <ul class="dropdown-menu">
    <li><a href="<%= edit_slide_path %>">Edit</a></li>
    <li><%= link_to t('.destroy', :default => t("helpers.links.destroy")), slide_path(s), method: :delete, data: { confirm: t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) } %></li>
    <li role="separator" class="divider"></li>
    <li><a href="#">Something else</a></li>
  </ul>
</li>
<% end %>

app/views/slides/edit.html.erb
<%= render :partial => 'menu_content', :locals => { :s => @slide } %>
<div class="container">
  <div class="row">
    <div class="col-xs-1">
      <%= link_to (slide_path) do %>
      <span class="glyphicon glyphicon-arrow-left"></span>
      <% end %>
    </div>
    <div class="col-xs-11">
      <h1>Editing Slide</h1>
    </div>
  </div>

  <%= render 'form', slide: @slide %>

</div>

app/views/slides/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <% @slides.each do |slide| %>
    <%= link_to (slide) do %>
      <div class="row text-center">
        <div class="row">
          <h3><%= slide.name %></h3>
        </div>
        <div class="row">
          <div class="col-md-2 col-md-offset-1">
            <%= slide.desc_left %>
          </div>
          <div class="col-md-6">
            <%= image_tag slide.picture.url(:medium) %>
          </div>
          <div class="col-md-2">
            <%= slide.desc_right %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/slides/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-1">
      <%= link_to (slides_path) do %>
      <span class="glyphicon glyphicon-arrow-left"></span>
      <% end %>
    </div>
    <div class="col-xs-11">
      <h1>New Slide</h1>
    </div>
  </div>
  <%= render 'form', slide: @slide %>
</div>

app/views/slides/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <div class="row">
    <div class="col-xs-1">
      <%= link_to (slides_path) do %>
      <span class="glyphicon glyphicon-arrow-left"></span>
      <% end %>
    </div>
    <div class="col-xs-11">
      <h1>
        <strong>Titre:</strong>
        <%= @slide.name %>
      </h1>
    </div>
  </div>
  <div class="row text-center">
    <div class="col-md-3">
      <p><strong>Description gauche :</strong></p>
      <p><%= @slide.desc_left %></p>
    </div>

    <div class="col-md-6">
      <%= image_tag @slide.picture.url(:medium) %>
    </div>

    <div class="col-md-3">
        <p><strong>Description droite :</strong></p>
        <p><%= @slide.desc_right %></p>
    </div>
  </div>
</div>